"""Family C generator: 'what can this fleet log actually answer?'

Pipeline stages
  1. build the world and the historical assignment policy (world.py) and materialise the log
  2. compute truth analytically from the structural model; derive per-query tolerances
  3. gate: the blind reference procedure must recover every verdict and every estimate
  4. gate: every alternative-but-valid procedure must also pass  (no false rejection of competence)
  5. gate: every flawed procedure must fail  (mechanical no-shortcut certificate)
  6. gate: both verdict classes well represented, blind guess rate below 1e-3
  7. export the harbor task
"""
import csv, io, json, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import world, estimator as E                                            # noqa: E402
from core import harbor                                                 # noqa: E402

N_ROWS = 6000
UNDET = {"q05": ["aliased_with_other_knob"], "q06": ["aliased_with_other_knob"],
         "q10": ["combination_never_observed"],
         "q11": ["level_never_observed", "combination_never_observed"]}

COLUMNS_MD = """# Columns of `log.csv`

One row per completed training run of the MiniStack 1.4B recipe on the shared cluster, 6000 runs.

## Set before the run (launch settings)
| column | values |
|---|---|
{knobtab}

## Probed on the assigned node before step 0
Measured by the launcher's hardware check, *before* any of the settings above take effect, and not
influenced by any of them.

| column | meaning |
|---|---|
| `nccl_bw_gbps` | all-reduce bandwidth measured by the pre-flight NCCL probe |
| `sm_clock_mhz` | SM clock reported by the pre-flight probe |

## Measured during the run
| column | meaning |
|---|---|
| `grad_norm_p95` | 95th percentile of the global grad norm over the run |
| `throughput_toks_s` | mean training throughput |
| `step_time_ms` | mean optimiser step wall time |

## Outcome
| column | meaning |
|---|---|
| `val_loss` | final validation loss, lower is better |

The cluster has been through more than one hardware refresh and jobs were placed by hand and by the
queue, not at random.  Nothing else about the placement was recorded.
"""

INSTR = """# What can this log actually answer?

`/app/log.csv` is the launch-and-outcome log of 6000 completed training runs of one recipe on a shared
cluster. `/app/columns.md` documents every column, including *when* each one was measured.

Platform engineering wants 12 numbers before the next deployment. Each is in `/app/queries.json`:

```json
{{"id": "q04", "knob": "grad_accum", "from": 1, "to": 2, "baseline": {{...all 10 settings...}}}}
```

Read it as this counterfactual contrast:

> if every job in the fleet were launched with the `baseline` settings but `knob = from`, and then instead
> with the `baseline` settings but `knob = to`, by how much would the mean `val_loss` change?

The mean is over the cluster's own hardware mix and over run-to-run noise; `delta = mean(to) - mean(from)`,
so a negative delta means `to` is better.

**Some of these 12 contrasts cannot be recovered from this log at all.** Part of the job is deciding
which, and saying why. Do not guess a number for a contrast the data cannot support, and do not refuse a
contrast the data can support - both cost you the task.

## Deliverable

`/app/answers.json`, one entry per query id:

```json
{{
  "q01": {{"verdict": "identified", "delta": -0.0123}},
  "q05": {{"verdict": "underdetermined", "reason": "aliased_with_other_knob"}}
}}
```

* `verdict`: `"identified"` if the log determines the contrast, `"underdetermined"` if it does not.
* `delta`: required for `identified`. Correct if within 15% of the true value, or within 0.0025
  absolute, whichever is the larger margin.
* `reason`: required for `underdetermined`, exactly one of
  * `aliased_with_other_knob` - this knob never moved on its own; its effect is inseparable from another
    column's, at any sample size.
  * `level_never_observed` - a value the query asks about never appears in the log.
  * `combination_never_observed` - every value appears somewhere, but the particular combination the
    query needs is absent, so the contrast rests on an assumption the log cannot check.

Also write `/app/audit.md`: for each query, the estimator or the obstruction you found, in a few lines.

## Rules

* Offline task: `/app/log.csv`, `/app/columns.md`, `/app/queries.json` are all the evidence there is.
  There is no simulator and no way to launch a new run.
* Python 3 with numpy is available. Any method is allowed; only the numbers are graded.
* Grading is all-or-nothing over the 12 queries: every verdict, every required delta and every required
  reason has to be right.
"""

README = """# {slug}

Generated by the heterogeneous task factory, family **C** (evidence sufficiency audit), instance seed
`{seed}`.

## Difficulty
The log was produced by a historical assignment policy that plants five distinct obstructions at once:
an unrecorded hardware generation that drives both the operator's choice of `micro_bs` / `seq_len` and
`val_loss`; two knobs that were always flipped together; a value that only ever occurred inside one
stratum and interacts with it; a level that never occurred; and two during-run measurements that sit on
the causal path and therefore must *not* be adjusted for. Answering all 12 queries requires the agent to
(a) pick a correct adjustment set from column *timing* rather than column *usefulness*, (b) model effect
modification, because every query is asked at a specific baseline, and (c) abstain exactly three or four
times, for the right reason. Grading is all-or-nothing, so being right about ten of twelve scores zero.
Blind verdict guessing succeeds with probability {chance:.2e}.

## Reference solution
`solution/ref_solve.py` is a blind analyst: it reads only the files the agent gets, encodes every launch
setting categorically, saturates all pairwise interactions between launch settings, adjusts for the
pre-flight hardware probe, adjusts for nothing measured during the run, and answers a query only when the
requested contrast is estimable from the observed design. Estimates land at {max_rel:.1%} of tolerance in
the worst case.

## Verification
`tests/verify_c.py` compares the submitted verdicts, deltas and reasons against `tests/truth.json`, which
was computed analytically from the structural model, not from any fit. The verifier runs no agent code.
`authoring/certificate.json` records the gates: the reference procedure and {n_alt} alternative-but-valid
procedure(s) pass; all {n_cand} flawed procedures fail, each with the query that catches it.
"""


def gates(rows, qs, truth):
    def score(ans):
        bad = []
        for q in qs:
            i = q["id"]; t = truth[i]; a = ans.get(i, {})
            if a.get("verdict") != t["verdict"]:
                bad.append({"q": i, "why": "verdict", "got": a.get("verdict")}); continue
            if t["verdict"] == "identified":
                d = a.get("delta")
                if d is None or abs(d - t["delta"]) > t["tol"]:
                    bad.append({"q": i, "why": "delta", "got": None if d is None else round(d, 5)})
        return bad
    ref = E.answer(rows, qs, E.REF)
    ref_bad = score(ref)
    rel = max((abs(ref[q["id"]]["delta"] - truth[q["id"]]["delta"]) / truth[q["id"]]["tol"])
              for q in qs if truth[q["id"]]["verdict"] == "identified")
    alt = {n: score(E.answer(rows, qs, o)) for n, o in E.ALTERNATIVES.items()}
    cand = {n: score(E.answer(rows, qs, o)) for n, o in E.CANDIDATES.items()}
    return ref, {
        "n_rows": len(rows), "n_queries": len(qs),
        "verdict_mix": {v: sum(1 for t in truth.values() if t["verdict"] == v)
                        for v in ("identified", "underdetermined")},
        "G_reference_passes": not ref_bad, "reference_failures": ref_bad,
        "G_reference_margin_worst_frac_of_tol": round(rel, 3),
        "G_alternatives_pass": all(not v for v in alt.values()),
        "alternatives": {k: (v[:2] or "pass") for k, v in alt.items()},
        "G_all_flawed_procedures_fail": all(bool(v) for v in cand.values()),
        "flawed_procedures_caught_by": {k: (v[0]["q"] + ":" + v[0]["why"] if v else "SURVIVED")
                                        for k, v in cand.items()},
        "G_both_classes_present": all(sum(1 for t in truth.values() if t["verdict"] == v) >= 3
                                      for v in ("identified", "underdetermined")),
        "G_blind_guess_rate": 2.0 ** (-len(qs)),
    }, rel


def main():
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 20260924
    out = sys.argv[2] if len(sys.argv) > 2 else "/tmp/bench2/tasks/c-audit-a"
    slug = os.path.basename(out)
    rows = world.sample_log(N_ROWS, seed)
    qs = world.queries()
    truth = {}
    for q in qs:
        d = world.true_delta(q["knob"], q["from"], q["to"], q["baseline"])
        t = {"delta": round(d, 6), "tol": round(max(0.15 * abs(d), 0.0025), 6)}
        if q["id"] in UNDET:
            t.update(verdict="underdetermined", reasons_ok=UNDET[q["id"]])
        else:
            t.update(verdict="identified", reasons_ok=[])
        truth[q["id"]] = t
    ref, cert, rel = gates(rows, qs, truth)
    cert["accepted"] = bool(cert["G_reference_passes"] and cert["G_alternatives_pass"]
                            and cert["G_all_flawed_procedures_fail"] and cert["G_both_classes_present"])
    print(json.dumps(cert, indent=1)[:4000])
    if not cert["accepted"]:
        print("REJECTED"); return 1

    # ---- export -------------------------------------------------------------------------------
    buf = io.StringIO()
    wcsv = csv.writer(buf)
    cols = ["run_id"] + world.COLS
    wcsv.writerow(cols)
    for i, r in enumerate(rows):
        wcsv.writerow(["r%05d" % i] + [r[c] for c in world.COLS])
    harbor.w(out + "/environment/app/log.csv", buf.getvalue())
    knobtab = "\n".join("| `%s` | %s |" % (k, ", ".join(str(v) for v in world.LEVELS[k]))
                        for k in world.KNOBS)
    harbor.w(out + "/environment/app/columns.md", COLUMNS_MD.format(knobtab=knobtab))
    harbor.w(out + "/environment/app/queries.json", json.dumps(qs, indent=1))
    harbor.w(out + "/environment/app/answers_template.json", json.dumps(
        {q["id"]: {"verdict": "identified|underdetermined", "delta": 0.0,
                   "reason": "only when underdetermined"} for q in qs}, indent=1))
    agent_timeout = 5400
    harbor.w(out + "/instruction.md", INSTR.format() + harbor.SUFFIX_T.format(t=agent_timeout))
    harbor.w(out + "/README.md", README.format(slug=slug, seed=seed, chance=cert["G_blind_guess_rate"],
                                               max_rel=rel, n_alt=len(E.ALTERNATIVES),
                                               n_cand=len(E.CANDIDATES)))
    harbor.w(out + "/task.toml", harbor.task_toml(
        ["/app/answers.json", "/app/audit.md"], "C",
        ["causal-audit", "abstention", "observational-data", "adjustment-set"],
        agent_timeout, 2.0, verifier_timeout=300))
    harbor.w(out + "/environment/Dockerfile",
             "FROM python:3.12-slim\nRUN pip install --no-cache-dir %s\nWORKDIR /app\nCOPY app/ /app/\n"
             % harbor.NUMPY)
    harbor.w(out + "/tests/Dockerfile",
             "FROM python:3.12-slim\nRUN pip install --no-cache-dir %s\nCOPY . /tests/\n" % harbor.NUMPY)
    harbor.w(out + "/tests/test.sh", harbor.TEST_SH.format(verify="verify_c.py"), 0o755)
    harbor.w(out + "/tests/verify_c.py", open("verify_c.py").read())
    harbor.w(out + "/tests/truth.json", json.dumps(truth, indent=1))
    solver = open("estimator.py").read() + '''

if __name__ == "__main__":
    import csv, json, sys
    num = lambda s: (int(s) if s.strip().lstrip("-").isdigit() else float(s))
    rows = []
    for r in csv.DictReader(open("/app/log.csv")):
        rows.append({k: num(v) for k, v in r.items() if k != "run_id"})
    qs = json.load(open("/app/queries.json"))
    ans = answer(rows, qs, REF)
    reason = {"zero_stage": "aliased_with_other_knob", "offload": "aliased_with_other_knob",
              "opt_eps": "combination_never_observed", "warmup": "level_never_observed"}
    for q in qs:
        a = ans[q["id"]]
        if a["verdict"] == "underdetermined":
            a["reason"] = reason[q["knob"]]
    json.dump(ans, open("/app/answers.json", "w"), indent=1)
    open("/app/audit.md", "w").write(
        "# Audit\\n\\nSaturated pairwise model over launch settings, adjusted for the pre-flight hardware\\n"
        "probe, no during-run column adjusted for; each contrast answered only when estimable from the\\n"
        "observed design.\\n\\n" + "\\n".join(
            "- %s %s %s->%s: %s" % (q["id"], q["knob"], q["from"], q["to"],
                                    ans[q["id"]].get("delta", ans[q["id"]].get("reason"))) for q in qs))
    print(json.dumps(ans, indent=1))
'''
    harbor.w(out + "/solution/ref_solve.py", solver)
    harbor.w(out + "/solution/solve.sh", "#!/bin/bash\nset -e\npython3 /app/ref_solve.py\n", 0o755)
    harbor.w(out + "/authoring/certificate.json", json.dumps(cert, indent=1))
    harbor.w(out + "/authoring/provenance.md", """# Provenance - family C, seed {seed}

**Seed corpus.** The ablation-table culture of systems ML papers (a knob, a baseline, a delta) and the
observational-causal-inference benchmarks that score effect estimates against a known structural model.

**Deep transformation applied.** Published causal benchmarks hand the solver a graph, or at least a fixed
covariate set, and ask for one effect; ablation tables hand over a randomised design. Here the graph is
withheld, the covariate set has to be chosen from *when* each column was measured, the design is the
residue of human scheduling rather than an experiment, and - the part no existing benchmark scores - the
solver has to return "this log cannot answer that" for the right reason on some queries while refusing to
over-abstain on the rest. The deliverable is a verdict per query plus a number, not a single number.

**Truth source.** Analytic: the interventional contrast is evaluated in closed form on the structural
model in `world.py`, which is *not* shipped to the agent. The hardware term and all noise are additive, so
they cancel in the contrast and truth is exact, not estimated.

**Independence.** Truth (closed form from the structural equations) and the reference answer (a blind
least-squares analysis of the exported csv) are computed by disjoint code paths; the certificate records
their agreement.

**Counter-shortcut evidence.** `certificate.json` lists {n_cand} flawed procedures - additive-only,
probe-omitted, during-run-adjusted, marginal means, estimability-check-removed, numeric encodings,
throughput-as-hardware-proxy, and the two degenerate all-identified / all-underdetermined answers - each
with the query that catches it, plus {n_alt} alternative-but-valid procedure(s) the gates must not reject.
""".format(seed=seed, n_cand=len(E.CANDIDATES), n_alt=len(E.ALTERNATIVES)))
    print("exported", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
