"""Build, certify and export `b-bounds-sealed`: the documentation-ablation arm of family B.

Same world, same estimand, same twenty-four bound items as `b-bounds-a`.  What changes is what the agent
is allowed to *read*:

  * the on-call incident write-up is replaced by a file inventory and a units note.  Nothing says when the
    quality check runs, what the two removal codes mean, or what the metric is rounded to;
  * `retention_log.csv` carries undocumented internal codes (`RSN-04`, `RSN-11`) instead of English
    reasons;
  * the metric card drops its statement about the rounding grid.

and what the agent has to *hand back*: eight single-run supports, which push the day-total constraint down
to the level of one run, plus an explicit statement of the mechanism it recovered - which code is the
quality check, and what grid the metric lives on.

The point of the arm is to separate two capabilities that the documented task scores together: applying a
censoring mechanism that someone else wrote down, and identifying one from the shape of the data.  The
documented arm measures the first and gives away the second.

Gates: G1-G8 as in `gen_b.py` (the world and the bound items are unchanged), plus

  G9a  the mechanism is *recoverable by program* - `discover_bs.py`, which reads only the agent-visible
       files, must return the screen code, the batch code and the grid that the key was built from, and
       must find the evidence on both sides (surviving rows below a later floor, none below their own);
  G9b  the grid is over-determined - the same gcd must come out of the recorded rows and the scraped
       percentages separately, so it is not an artefact of one source;
  G9c  the single-run items earn their place - all three missing-data classes present with three different
       bound shapes, at least one run the published day total pins outright inside a box far wider than
       the tolerance, at least one run whose lower end the total lifts without pinning, at least one run
       sitting on a policy changeover, and at least four decoys that only these items expose;
  G9d  no document in the sealed environment contains the English reason names, the incident ids, or the
       phrases that would give the mechanism away.
"""
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "core"))
import bounds_b as B                                                         # noqa: E402
import discover_bs as D                                                      # noqa: E402
import gen_b as G                                                            # noqa: E402
import harbor as H                                                           # noqa: E402
import truth_b as T                                                          # noqa: E402
import world_b as W                                                          # noqa: E402

TOL = G.TOL
N_SUPPORT = 8
OUT = sys.argv[1] if len(sys.argv) > 1 else "/tmp/bench2/tasks/b-bounds-sealed"
CODE = {"below_retention_floor": "RSN-04", "shard_file_lost": "RSN-11"}
BANNED = ["below_retention_floor", "shard_file_lost", "INC-4471", "INC-4506", "incident", "outage",
          "quality screen", "write-time", "survivor", "four decimals", "0.0001", "screen"]

OPS = """# Archive notes - 2026-06 evaluation sweep

What follows is a file inventory and a units note.  It is not an explanation: nobody reconstructed why
each missing number is missing, and the internal codes in `retention_log.csv` are generated by the
archiver and are not documented anywhere.

## Files

  * `plan.csv` - every run that was scheduled, with its four configuration knobs.
  * `launch_log.csv` - the runs that actually started, and the worker each one ran on.
  * `eval_results.csv` - the `pass_rate` rows the archive still holds.
  * `retention_log.csv` - rows the archive no longer holds: the run id, the instant the row left the
    store, and an internal code in the `reason` column.
  * `retention_policy.json` - the versioned quality floor the archiver is configured with.  Intervals are
    half-open: `[from, to)`.
  * `recovered/*.csv` - values scraped out of the per-worker stdout tails, one file per collection pass.
    The stdout banner prints the score as a percentage, so these carry `pass_rate_pct`; it is the same
    quantity as `pass_rate`, in different units.  The scrape was opportunistic and the shard files were
    assembled from planning tickets, so: a run can appear in several shards and in `eval_results.csv` as
    well, a few rows are duplicated, and a few run ids belong to runs that never launched.  Where a run
    appears more than once the values agree.  Treat the shards as a value source, never as a run list.
  * `runtime.csv` - when each launched run finished.  Kept by the scheduler, on a different host from the
    archive.
  * `daily_digest.csv` - for each UTC day, how many runs finished that day and what their `pass_rate`
    values added up to.  Written at 23:59 from the scores the scheduler received directly from each
    worker, so its totals cover every run that finished that day, whatever the archive did with the row.
    The figure it prints is the exact total, not a rounded summary of one.
  * `suites.json` - for each suite, how the harness scores it.
  * `metric_card.md` - what `pass_rate` means.

## Storage layout

The archive holds result rows in one file per worker per UTC day.

## What is known to be complete

`plan.csv`, `launch_log.csv`, `retention_log.csv`, `runtime.csv` and `daily_digest.csv` are complete for
the whole sweep: nothing was removed from them and no row in them is wrong.  Every file in `/app` is
exactly what it claims to be.

## What is known to be missing

Some launched runs have no row in `eval_results.csv`.  Some of those appear in `retention_log.csv` and
some do not.
"""

METRIC = """# `pass_rate`

Every run reports exactly one number, `pass_rate`, on the suite named in its plan row.  What the harness
writes depends on how the suite is scored, which `suites.json` records along with `random_guess`, the
score an uninformed answer earns on that suite:

  * `scoring: "raw"` - the fraction of the suite's items the run passed, reported as is, except that the
    harness never emits a value below `random_guess`: a run that scores under the baseline is written out
    at the baseline.
  * `scoring: "normalized"` - the raw fraction rescaled so that `random_guess` maps to 0 and a perfect
    run maps to 1, clipped below at 0.

Either way the number lies in [0, 1].
"""

INSTR = """You are the on-call analyst for a model-evaluation fleet.  A six-week sweep finished; the
archive in `/app` is what survived of it.

Every planned run appears in `plan.csv` with its four configuration knobs (`suite`, `curriculum`,
`retrieval`, `decoder`).  `launch_log.csv` says which of them actually started.  Each launched run
produced a single number, its `pass_rate` on the suite it was assigned - and the archive no longer holds
all of those numbers.  `archive_notes.md` inventories the files and `metric_card.md` says what the number
means.  Neither of them explains the gaps, and nobody is left who can: the `reason` column of
`retention_log.csv` holds internal archiver codes with no published meaning, and no write-up of the
sweep survives.  Every file in `/app` is exactly what it claims to be and no file is wrong, but what each
surviving record still implies about a missing value is entirely for you to establish from the records
themselves.

Your job is *not* to guess the missing numbers.  It is to report exactly what the surviving records still
pin down about them - no more and no less - and to state the mechanism you concluded was at work.

## The quantity

Fix a configuration `c` (one value for each of the four knobs).  `L(c)` is the set of run ids that appear
in `launch_log.csv` *and* whose `plan.csv` row has exactly those four knob values; count each run id once,
however many rows mention it.  `N(c) = |L(c)|`.

`m(c)` is the plain average of the true `pass_rate` of the runs in `L(c)`, over all `N(c)` of them,
including the ones whose value the archive no longer holds.  Every launched run has a true `pass_rate`;
the archive's failure to keep it does not remove the run from the average.  `m(c)` is a property of these
particular runs, not of some larger population - there is nothing to extrapolate to and nothing to
resample.

## What to report

Call an assignment of a value to every launched run whose `pass_rate` the archive does not hold
*consistent* if it contradicts nothing in `/app`.  For each item in `/app/queries.json`, report the
**sharp** interval: the smallest closed interval containing the quantity's value under every consistent
assignment.  An interval that is correct but wider than necessary is wrong, and so is a single number
reported as a degenerate interval when the quantity is not pinned down.

  * `cells`: the interval for `m(c)`.
  * `contrasts`: the interval for `m(to) - m(from)`.
  * `decisions`: is `m(to) - m(from)` greater than `margin`?  Answer `"yes"` if that holds under every
    consistent assignment, `"no"` if it holds under none of them, and `"cannot_tell"` otherwise.
  * `supports`: the interval for one named run's own true `pass_rate`.
  * `mechanism`: two claims about how the archive came to be missing what it is missing.  `screen_code`
    is the code in the `reason` column of `retention_log.csv` under which a row was removed *because of
    the value it held*; the other code, whatever it is, removed rows for a reason that has nothing to do
    with their values.  `grid` is the positive number that every true `pass_rate` in this sweep is an
    exact multiple of - recorded, removed, or never recorded.  Both are determined by the files; neither
    is a matter of taste.

Write `/app/answers.json`:

```json
{
  "cells":     {"b01": {"lo": 0.4131, "hi": 0.4131}},
  "contrasts": {"k01": {"lo": -0.0182, "hi": 0.0413}},
  "decisions": {"d01": "cannot_tell"},
  "supports":  {"s01": {"lo": 0.05, "hi": 0.2699}},
  "mechanism": {"screen_code": "RSN-00", "grid": 0.01}
}
```

Every id in `queries.json` must appear.  Interval endpoints are graded to an absolute tolerance of 5e-4,
so give at least four decimals; the answer is exact arithmetic, not an estimate.  `grid` is graded
exactly.  Scoring is all-or-nothing over the %d items.  Do not edit anything under `/app` except
`answers.json`.
"""


def emit(app, w):
    """The sealed archive: same bytes as the documented arm except for the reason column and the prose."""
    G.emit(app, w)
    os.remove(os.path.join(app, "incidents.md"))
    H.csv_rows(os.path.join(app, "retention_log.csv"), ["run_id", "dropped_at", "reason"],
               [dict(r, reason=CODE[r["reason"]]) for r in w["retention"]])
    H.w(os.path.join(app, "archive_notes.md"), OPS)
    H.w(os.path.join(app, "metric_card.md"), METRIC)


def classify(arch):
    """The three missing-data classes, by the evidence the archive offers - values excluded."""
    out = {"screened": [], "worker_day_lost": [], "no_row_no_entry": []}
    for rid in sorted(arch.launched):
        if rid in arch.res or rid in arch.rec:
            continue                              # a known value makes the support degenerate
        e = arch.drop.get(rid)
        k = ("screened" if e and e["reason"] == "below_retention_floor" else
             "worker_day_lost" if e else "no_row_no_entry")
        out[k].append(rid)
    return out


def pick_supports(arch):
    """Eight runs, chosen for the *shape* of what is known about them rather than at random.

    A configuration mean over thirty-odd runs hides how each individual value is constrained; asking for
    one run's own value does not.  The eight slots are therefore filled by kind, and the gate checks that
    each kind is present:

      * a run that finished on a day where it is the *only* unrecorded run, so the published daily total
        determines its value exactly - the box around it is wide and the answer is a point.  An agent that
        treats single-run bounds as box arithmetic reports an interval here and fails;
      * a run that finished at the exact instant a retention policy version changed, where the half-open
        convention is the entire answer;
      * a run sharing its day with one other unknown, so the total lifts its lower end without pinning it;
      * a run on a crowded day, where the box really is the answer - the control;
      * two runs removed with their worker-day file, whose lower end is lifted by a floor they are only
        known to have cleared by inference;
      * two runs with no row and no removal entry, one on a raw-scored suite and one on a normalised one,
        which are bounded by nothing but the metric's own range.
    """
    ctx = B.Ctx(arch, B.REF)
    edges = {p["from"] for p in arch.policy[1:]}
    cand = []
    for cls, rids in sorted(classify(arch).items()):
        for rid in rids:
            lo, hi = ctx.run_support(rid)
            box = ctx.sup[rid]
            cand.append({"run_id": rid, "class": cls, "lo": lo, "hi": hi, "box": list(box),
                         "bind": round((box[1] - hi) + (lo - box[0]), 6), "pinned": hi - lo < 1e-9,
                         "peers": len(ctx.unk[ctx.day[rid]]) - 1, "suite": arch.suite_of[rid],
                         "on_edge": arch.finished_at[rid] in edges,
                         "base": arch.floor(arch.suite_of[rid], B.REF)})
    slots = [
        ("pinned_by_its_day_total", lambda c: c["class"] == "screened" and c["pinned"],
         lambda c: (-(c["box"][1] - c["box"][0]), c["run_id"])),
        ("finished_on_a_policy_edge", lambda c: c["class"] == "screened" and c["on_edge"],
         lambda c: (c["run_id"],)),
        ("lifted_but_not_pinned", lambda c: (c["class"] == "screened" and c["bind"] > 0
                                             and not c["pinned"]), lambda c: (-c["bind"], c["run_id"])),
        ("box_is_the_answer", lambda c: c["class"] == "screened" and c["bind"] == 0,
         lambda c: (-c["box"][1], c["run_id"])),
        ("worker_day_lost_low_base", lambda c: c["class"] == "worker_day_lost",
         lambda c: (c["base"], c["run_id"])),
        ("worker_day_lost_high_base", lambda c: c["class"] == "worker_day_lost",
         lambda c: (-c["base"], c["run_id"])),
        ("unlogged_raw_suite", lambda c: c["class"] == "no_row_no_entry" and c["base"] > 0,
         lambda c: (-c["base"], c["run_id"])),
        ("unlogged_normalised_suite", lambda c: c["class"] == "no_row_no_entry" and c["base"] == 0,
         lambda c: (c["run_id"],)),
    ]
    chosen, seen = [], set()
    for role, pred, key in slots:
        pool = sorted([c for c in cand if pred(c) and c["run_id"] not in seen], key=key)
        assert pool, ("no run available for support slot %s" % role)
        pick = dict(pool[0], role=role)
        seen.add(pick["run_id"])
        chosen.append(pick)
    chosen.sort(key=lambda s: (s["class"], s["run_id"]))
    for i, s in enumerate(chosen):
        s["id"] = "s%02d" % (i + 1)
    return chosen


def scan(arch, queries):
    """Decoy scan extended to the support section, reported verbatim in the certificate."""
    ref = B.answer(arch, queries, B.REF)
    rows = {}
    for name, spec in B.CANDIDATES.items():
        got = B.answer(arch, queries, spec)
        bad, worst, sup = [], 0.0, []
        for k in ("cells", "contrasts", "supports"):
            for qid in ref[k]:
                d = max(abs(ref[k][qid]["lo"] - got[k][qid]["lo"]),
                        abs(ref[k][qid]["hi"] - got[k][qid]["hi"]))
                if d > TOL:
                    bad.append(qid)
                    worst = max(worst, d)
                    if k == "supports":
                        sup.append(qid)
        for qid in ref["decisions"]:
            if ref["decisions"][qid] != got["decisions"][qid]:
                bad.append(qid)
        rows[name] = {"n_fail": len(bad), "items": bad[:6], "worst_endpoint_error": round(worst, 5),
                      "support_items_failed": sup}
    return rows


def certify_sealed(arch, w, queries, sup):
    """G9a-G9d.  Everything before them is `gen_b.certify`, run on the same world."""
    cert = {}
    found = D.discover(arch.app)
    cert["G9a_mechanism_recoverable_by_program"] = found
    assert found["screen_code"] == CODE["below_retention_floor"], found
    assert found["batch_code"] == CODE["shard_file_lost"], found
    assert found["surviving_rows_below_their_own_finish_floor"] == 0, found
    assert found["surviving_rows_below_the_latest_floor"] >= 50, found
    assert found["runs_refuting_a_bound_on_the_unlogged_class"] >= 3, found
    assert found["worker_day_lost_runs_whose_bound_actually_lifts"] >= 10, found
    assert abs(found["grid"] - B.GRID) < 1e-12, found

    cert["G9b_grid_over_determined"] = found["grid_per_source"]
    assert all(abs(v - B.GRID) < 1e-12 for v in found["grid_per_source"].values()), found

    # G9c: the support items must (i) agree with the independent implementation, (ii) contain the hidden
    # value, (iii) have attainable endpoints, (iv) cover all three missing-data classes with the three
    # different bound shapes, (v) include at least one run the day total pins outright, and (vi) expose
    # decoys of their own.
    hid = w["hidden"]
    ctx = B.Ctx(arch, B.REF)
    ind = T.Truth(arch.app)
    rowsb, worst_ind = [], 0.0
    for s in sup:
        rid = s["run_id"]
        lo, hi = ctx.run_support(rid)
        a, b = ind.one(rid)
        worst_ind = max(worst_ind, abs(float(a) - lo), abs(float(b) - hi))
        assert lo - 1e-9 <= hid[rid] <= hi + 1e-9, ("hidden value outside its own support", rid)
        for side, want in (("lo", lo), ("hi", hi)):
            d = ctx.day[rid]
            peers = [r for r in ctx.unk[d] if r != rid]
            rest = ctx.R[d] - want
            assert (sum(ctx.sup[r][0] for r in peers) - 1e-9 <= rest
                    <= sum(ctx.sup[r][1] for r in peers) + 1e-9), ("endpoint not attainable", rid, side)
        rowsb.append({"id": s["id"], "run_id": rid, "class": s["class"], "role": s["role"],
                      "lo": round(lo, 6), "hi": round(hi, 6), "box": [round(x, 6) for x in s["box"]],
                      "tightened_by_the_daily_total": s["bind"], "unknown_peers_that_day": s["peers"],
                      "finished_on_a_policy_edge": s["on_edge"], "hidden": hid[rid]})
    shape = {}
    for r, s in zip(rowsb, sup):
        above = r["box"][1] < 1.0 - 1e-9
        below = r["box"][0] > s["base"] + 1e-9
        shape[r["id"]] = ("above" if above and not below else "below" if below and not above
                          else "both" if above else "neither")
    cert["G9c_single_run_items"] = {
        "items": rowsb, "independent_agreement": round(worst_ind, 9), "bound_shape": shape,
        "classes": sorted({r["class"] for r in rowsb}),
        "pinned_outright": [r["id"] for r in rowsb if r["hi"] - r["lo"] < 1e-9],
        "box_width_of_the_pinned_items": [round(r["box"][1] - r["box"][0], 6) for r in rowsb
                                          if r["hi"] - r["lo"] < 1e-9]}
    assert worst_ind < 1e-6, worst_ind
    assert len({r["class"] for r in rowsb}) == 3, rowsb
    assert set(shape.values()) >= {"above", "below", "neither"}, shape
    pin = [r for r in rowsb if r["hi"] - r["lo"] < 1e-9]
    assert pin and min(r["box"][1] - r["box"][0] for r in pin) > 10 * TOL, pin
    assert any(0 < r["tightened_by_the_daily_total"] and r["hi"] - r["lo"] > 1e-9 for r in rowsb), rowsb
    assert any(r["finished_on_a_policy_edge"] for r in rowsb), rowsb

    sc = scan(arch, queries)
    only = {n: v["support_items_failed"] for n, v in sc.items() if v["support_items_failed"]}
    cert["G9c_decoys_the_support_items_expose"] = only
    assert len(only) >= 4, only

    # G9d: no *document* in the environment leaks the words the arm exists to withhold.  The scan is over
    # prose and configuration, not over the data files: a `pass_rate` that happens to read 0.0001 is a
    # measurement, not a statement about the grid, and banning digit strings from the data would be
    # theatre.
    leaks = []
    for dirpath, _, names in os.walk(arch.app):
        for n in sorted(names):
            if not (n.endswith(".md") or n.endswith(".json")):
                continue
            p = os.path.join(dirpath, n)
            txt = open(p, errors="replace").read().lower()
            for word in BANNED:
                if word.lower() in txt:
                    leaks.append([os.path.relpath(p, arch.app), word])
    cert["G9d_no_leak_in_the_environment"] = {"documents_scanned": sorted(
        n for n in os.listdir(arch.app) if n.endswith((".md", ".json"))), "leaks": leaks}
    assert not leaks, leaks
    return cert, sc


def main():
    w = W.build(0)
    app = os.path.join(OUT, "environment", "app")
    if os.path.exists(OUT):
        shutil.rmtree(OUT)
    os.makedirs(app)
    emit(app, w)
    arch = B.Arch(app)
    items = G.build_items(arch, G.launched_cells(arch))
    queries, need, _, killable = G.select(arch, items)
    sup = pick_supports(arch)
    queries["supports"] = [{"id": s["id"], "run_id": s["run_id"]} for s in sup]
    cert, ref = G.certify(arch, w, queries)
    cert2, sc = certify_sealed(arch, w, queries, sup)
    cert.update(cert2)
    short = {n: k for n, k in need.items() if k > 0}
    cert["G5_selection"] = {"underkilled": short, "items_able_to_kill_each_decoy": killable,
                            "decoys": sc}
    cert["G7_tolerance"] = {"tol": TOL, "min_decoy_endpoint_error":
                            round(min([v["worst_endpoint_error"] for v in sc.values()
                                       if v["worst_endpoint_error"] > 0] or [0]), 5)}
    ok = (not short) and all(v["n_fail"] >= G.MIN_FAIL for v in sc.values())

    full = B.answer(arch, queries, B.REF)
    ind = T.solve(app, queries)
    bad = [s["id"] for s in sup
           if max(abs(full["supports"][s["id"]][e] - ind["supports"][s["id"]][e])
                  for e in ("lo", "hi")) > 1e-6]
    assert not bad, bad
    json.dump(queries, open(os.path.join(app, "queries.json"), "w"), indent=1)
    n_items = (len(queries["cells"]) + len(queries["contrasts"]) + len(queries["decisions"])
               + len(queries["supports"]) + 2)
    key = {"tol": TOL, "cells": full["cells"], "contrasts": full["contrasts"],
           "decisions": full["decisions"], "supports": full["supports"],
           "mechanism": {"screen_code": CODE["below_retention_floor"], "grid": B.GRID,
                         "codes_present": sorted(CODE.values())}}

    H.w(os.path.join(OUT, "instruction.md"), INSTR % n_items + H.SUFFIX_T.format(t=5400))
    H.w(os.path.join(OUT, "task.toml"),
        H.task_toml(artifacts=["answers.json"], family="b-bounds-sealed",
                    tags=["partial-identification", "missing-data", "mechanism-identification",
                          "ai4ai-eval"],
                    agent_timeout=5400, expert_hours=3.5, verifier_timeout=300))
    os.makedirs(os.path.join(OUT, "tests"))
    shutil.copy(os.path.join(HERE, "verify_bs.py"), os.path.join(OUT, "tests", "verify_bs.py"))
    json.dump(key, open(os.path.join(OUT, "tests", "key.json"), "w"), indent=1)
    H.w(os.path.join(OUT, "tests", "test.sh"), "#!/bin/bash\nset -eu\npython3 /tests/verify_bs.py\n",
        mode=0o755)
    H.w(os.path.join(OUT, "tests", "Dockerfile"),
        "FROM python:3.11-slim\nCOPY verify_bs.py key.json test.sh /tests/\n")
    os.makedirs(os.path.join(OUT, "solution"))
    for f in ("bounds_b.py", "truth_b.py", "discover_bs.py", "ref_solve_bs.py"):
        shutil.copy(os.path.join(HERE, f), os.path.join(OUT, "solution", f))
    H.w(os.path.join(OUT, "solution", "solve.sh"),
        "#!/bin/bash\nset -eu\npython3 /solution/ref_solve_bs.py /app\n", mode=0o755)
    os.makedirs(os.path.join(OUT, "authoring"))
    json.dump({"accepted": ok, "n_items": n_items, "gates": cert},
              open(os.path.join(OUT, "authoring", "certificate.json"), "w"), indent=1)

    print("items", {k: len(v) for k, v in queries.items()}, "+2 mechanism ->", n_items)
    for r in cert["G9c_single_run_items"]["items"]:
        print("  %s %-16s %-7s box=%s sharp=[%.4f, %.4f] tightened=%.4f edge=%s"
              % (r["id"], r["run_id"], r["class"], r["box"], r["lo"], r["hi"],
                 r["tightened_by_the_daily_total"], r["finished_on_a_policy_edge"]))
    print("  discovered:", json.dumps({k: cert["G9a_mechanism_recoverable_by_program"][k]
                                       for k in ("screen_code", "batch_code", "grid")}))
    for n, v in sorted(sc.items(), key=lambda x: x[1]["n_fail"]):
        print("  %-48s n_fail=%-3d worst=%.4f sup=%s" % (n, v["n_fail"], v["worst_endpoint_error"],
                                                         v["support_items_failed"][:3]))
    print("underkilled:", short)
    print("accepted:", ok)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
