"""Family V generator: falsification / witness construction over a data-preparation stack.

Gates
  G1 every falsifiable claim has a reference witness the verifier confirms  (existence proof)
  G2 every claim recorded as holding survives a fuzzer                      (no wrong key entries)
  G3 the hard claim is not reachable by random search                       (construction is required)
  G4 degenerate and out-of-scope witnesses are rejected                     (no loophole witnesses)
  G5 the degenerate blanket answers fail                                    (no base-rate shortcut)
"""
import json, os, random, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(HERE, "dataprep"))
import claims as C, make_witnesses as M                                           # noqa: E402
import dedup                                                                      # noqa: E402
from core import harbor                                                           # noqa: E402

KEY = {"V1": "violated", "V2": "violated", "V3": "violated", "V4": "holds", "V5": "holds",
       "V6": "violated"}

CLAIMS_MD = """# Design-doc claims about `/app/dataprep`

Six claims the data team wrote down about the pipeline. Each is either true of the code as shipped, or
false. A claim is false only if some input **inside its stated scope** violates it.

{body}
## Witness schemas

A witness is a JSON file. One object per claim, exactly these fields:

{schemas}
"""

INSTR = """# Falsify the data team's promises

`/app/dataprep/` is MiniStack's data preparation stack: near-duplicate removal, decontamination,
sharding, packing, streaming shuffle, and the per-epoch sampler. `/app/CLAIMS.md` lists six claims the
design doc makes about these modules, each with the scope it is asserted over and the schema of a witness
against it.

Some of the claims are true of the code as shipped. Some are false. Your job is to say which, and to
*prove* the false ones with a concrete input.

Beware: at least one of the false claims fails only on inputs that must be constructed deliberately -
sampling inputs at random and hoping to trip it will not work, and neither will assuming that a claim
about a probabilistic algorithm must be false just because the algorithm is probabilistic.

## Deliverable

`/app/findings.json`, one entry per claim id:

```json
{{
  "V3": {{"status": "violated", "witness": "witnesses/v3.json"}},
  "V4": {{"status": "holds",    "argument": "why no input in scope can violate it, >= 80 characters"}}
}}
```

Write each witness as a JSON file somewhere under `/app` and give its path relative to `/app`
(at most 2 MiB each).

## How it is graded

* A `violated` answer counts only if the witness parses, lies inside the claim's published scope, and an
  independent check - one that recomputes the claimed quantity from the witness itself rather than
  trusting the module - confirms that the module breaks the claim on it.
* A `holds` answer counts only if the claim really is unfalsifiable within its scope. The argument text is
  required but is not itself graded.
* A confirmed witness is always accepted, including for a claim the grader expected to hold. Finding
  something the authors missed cannot cost you anything.
* The grader imports its own pristine copy of `dataprep`. Editing `/app/dataprep` changes nothing; you are
  free to copy, instrument and experiment with it.
* Grading is all-or-nothing over the six claims.

Python 3 with numpy is available and there is no network.
"""

README = """# {slug}

Generated by the heterogeneous task factory, family **V** (invariant falsification), instance seed
`{seed}`.

## Difficulty
Four of the six claims are false, two are true, and the task is scored all-or-nothing, so the agent has to
be right about both directions: invent counterexamples *and* decline to invent them. Three of the four
falsifications are ordinary bug-spotting (a pad-to-multiple that repeats the last index, a
case-folding asymmetry between index build and index query, a block shuffle that drops the tail).
The fourth, V1, is the discriminator: the MinHash banding is {bands} bands of {rows} rows, so a random
pair at Jaccard 0.9 escapes with probability {p_rand:.1e} - measured random search over
{n_rand} near-duplicate pairs found {n_rand_hits} witnesses. A witness has to be engineered by choosing
appended shingles whose permuted hashes fall below the document's per-row minima, one row per band. The
two true claims are each fuzzed with {n_fuzz} random inputs without a single violation, so an agent that
answers "violated" everywhere loses.

## Reference solution
`solution/make_witnesses.py` builds all four witnesses, V1 included, in {v1_s:.2f} s of hash probing.

## Verification
`tests/verify_v.py` re-derives the claimed quantity from the witness itself (its own shingling, its own
n-gram extraction, its own assignment counting) before calling the module, and imports the pristine
modules from `/tests`, never the agent's copy. There is no numeric answer key for the falsifiable claims:
a witness proves itself. Grading is deliberately asymmetric - a confirmed witness is accepted even for a
claim the key records as holding, so an agent that out-audits the authors is never punished.
`authoring/certificate.json` records every gate.
"""


def fuzz_holding(n, seed):
    rng = random.Random(seed)
    bad = []
    for _ in range(n):
        L = [rng.choice([0, 1, 2, 7, 64, 1000, 10 ** 6]) for _ in range(rng.randint(1, 40))]
        mt = rng.choice([1, 2, 3, 64, 999, 10 ** 6])
        try:
            v, d = C.v4({"lengths": L, "max_tokens": mt})
        except ValueError:
            continue
        if v:
            bad.append(("V4", L, mt, d))
    for _ in range(n):
        k = rng.randint(1, 60)
        items = [rng.randint(0, 5) for _ in range(k)]
        bs = rng.randint(1, 70)
        v, d = C.v5({"items": items, "buffer_size": bs, "seed": rng.randint(0, 10 ** 6)})
        if v:
            bad.append(("V5", items, bs, d))
    return bad


def random_search_v1(n_pairs, seed, n_words=320, frac=0.09):
    """Naive strategy for V1: perturb a document and hope the pair slips past the banding."""
    rng = random.Random(seed)
    hits = 0
    for _ in range(n_pairs):
        base = [rng.choice(M.WORDS) for _ in range(n_words)]
        b = list(base)
        for i in rng.sample(range(n_words), int(frac * n_words)):
            b[i] = "q%d" % rng.randint(0, 10 ** 6)
        da, db = " ".join(base), " ".join(b)
        sa, sb = dedup.shingles(da), dedup.shingles(db)
        if len(sa & sb) / len(sa | sb) < 0.80:
            continue
        if len(dedup.dedup([da, db])) == 2:
            hits += 1
    return hits


def grade(app, tests):
    logs = tempfile.mkdtemp()
    env = dict(os.environ, APP=app, TESTS=tests, REWARD_DIR=logs)
    p = subprocess.run([sys.executable, os.path.join(tests, "verify_v.py")], env=env,
                       capture_output=True, text=True, timeout=900)
    try:
        return json.loads(p.stdout.strip().splitlines()[-1])
    except Exception:
        return {"reward": None, "stderr": p.stderr[-400:]}


def main():
    import time
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 20260924
    out = sys.argv[2] if len(sys.argv) > 2 else "/tmp/bench2/tasks/v-falsify-a"
    slug = os.path.basename(out)
    n_fuzz, n_rand = 4000, 1200

    t0 = time.time()
    ref = {}
    for cid, fn in M.BUILDERS.items():
        wit, note = fn()
        conf, det = C.CHECK[cid](wit)
        ref[cid] = {"confirmed": bool(conf), "note": note, "check": det}
    v1_s = time.time() - t0
    fz = fuzz_holding(n_fuzz, seed)
    hits = random_search_v1(n_rand, seed)
    p_rand = (1 - 0.9 ** dedup.ROWS) ** dedup.BANDS

    scope = []
    for name, wit, why in [
        ("V1_two_short_identical_docs", {"docs": ["a b c d e f" * 10, "a b c d e f" * 10]}, "too few tokens"),
        ("V3_drop_last_true", {"n": 10, "world_size": 4, "drop_last": True}, "out of scope"),
        ("V3_world_size_zero", {"n": 10, "world_size": 0, "drop_last": False}, "world_size out of range"),
        ("V6_n_zero", {"n": 0, "seed": 1, "epoch": 0}, "n out of range"),
        ("V1_low_jaccard", {"docs": [" ".join(M.WORDS * 10), " ".join(sorted(M.WORDS) * 10)]},
         "similarity below the scope threshold")]:
        cid = name.split("_")[0]
        try:
            C.CHECK[cid](wit)
            scope.append({"witness": name, "rejected": False, "expected": why})
        except ValueError as e:
            scope.append({"witness": name, "rejected": True, "reason": str(e)[:80]})

    cert = {
        "n_claims": len(KEY), "key": KEY,
        "G1_reference_witnesses_confirmed": all(v["confirmed"] for v in ref.values()),
        "reference_witnesses": {k: {"confirmed": v["confirmed"], "check": v["check"]}
                                for k, v in ref.items()},
        "G2_holding_claims_survive_fuzz": not fz, "n_fuzz_per_claim": n_fuzz, "fuzz_violations": fz[:3],
        "G3_random_search_fails_on_V1": hits == 0, "n_random_pairs": n_rand, "random_search_hits": hits,
        "V1_analytic_escape_probability_at_jaccard_0.9": p_rand,
        "G4_out_of_scope_witnesses_rejected": all(s["rejected"] for s in scope), "scope_probes": scope,
        "G5_blanket_answer_guess_rate": 2.0 ** -len(KEY),
        "v1_construction_seconds": round(v1_s, 2),
    }
    cert["accepted"] = bool(cert["G1_reference_witnesses_confirmed"] and cert["G2_holding_claims_survive_fuzz"]
                            and cert["G3_random_search_fails_on_V1"]
                            and cert["G4_out_of_scope_witnesses_rejected"])
    print(json.dumps({k: v for k, v in cert.items() if k not in ("reference_witnesses", "scope_probes")},
                     indent=1))
    if not cert["accepted"]:
        print("REJECTED", json.dumps(cert)[:2000]); return 1

    # ---- export -------------------------------------------------------------------------------
    for d in ("/environment/app/dataprep", "/tests/dataprep", "/solution/dataprep"):
        os.makedirs(out + d, exist_ok=True)
        for f in sorted(os.listdir(os.path.join(HERE, "dataprep"))):
            if f.endswith(".py"):
                shutil.copy(os.path.join(HERE, "dataprep", f), out + d + "/" + f)
    body = "\n".join("### %s\n\n%s\n" % (c, C.CLAIM_TEXT[c]) for c in sorted(KEY))
    schemas = "\n".join("* **%s** `%s`" % (c, C.SCHEMA[c]) for c in sorted(KEY))
    harbor.w(out + "/environment/app/CLAIMS.md", CLAIMS_MD.format(body=body, schemas=schemas))
    agent_timeout = 5400
    harbor.w(out + "/instruction.md", INSTR.format() + harbor.SUFFIX_T.format(t=agent_timeout))
    harbor.w(out + "/README.md", README.format(slug=slug, seed=seed, bands=dedup.BANDS, rows=dedup.ROWS,
                                               p_rand=p_rand, n_rand=n_rand, n_rand_hits=hits,
                                               n_fuzz=n_fuzz, v1_s=v1_s))
    harbor.w(out + "/task.toml", harbor.task_toml(
        ["/app/findings.json"], "V",
        ["falsification", "counterexample-construction", "data-pipeline", "invariants"],
        agent_timeout, 2.5, verifier_timeout=600))
    harbor.w(out + "/environment/Dockerfile",
             "FROM python:3.12-slim\nRUN pip install --no-cache-dir %s\nWORKDIR /app\nCOPY app/ /app/\n"
             % harbor.NUMPY)
    harbor.w(out + "/tests/Dockerfile",
             "FROM python:3.12-slim\nRUN pip install --no-cache-dir %s\nCOPY . /tests/\n" % harbor.NUMPY)
    harbor.w(out + "/tests/test.sh", harbor.TEST_SH.format(verify="verify_v.py"), 0o755)
    harbor.w(out + "/tests/verify_v.py", open(os.path.join(HERE, "verify_v.py")).read())
    harbor.w(out + "/tests/claims.py", open(os.path.join(HERE, "claims.py")).read())
    harbor.w(out + "/tests/key.json", json.dumps(KEY, indent=1))
    harbor.w(out + "/solution/make_witnesses.py", open(os.path.join(HERE, "make_witnesses.py")).read())
    harbor.w(out + "/solution/solve.sh",
             "#!/bin/bash\nset -e\ncd /app\npython3 /app/make_witnesses.py /app\n", 0o755)
    harbor.w(out + "/authoring/certificate.json", json.dumps(cert, indent=1))
    harbor.w(out + "/authoring/provenance.md", """# Provenance - family V, seed {seed}

**Seed corpus.** Real data-infrastructure incidents: MinHash/LSH deduplication recall, n-gram
decontamination that normalises one side only, `pad_to_multiple` sharding that repeats the tail document,
block-local shuffling that drops the remainder.

**Deep transformation applied.** Bug-finding benchmarks (SWE-bench and its relatives) give the solver a
failing test and ask for a patch; the failure is handed over. Here nothing fails: the code runs, the
pipeline produces plausible output, and the *claims* are the artefact under test. The deliverable is a
constructed input, not a patch, and the solver must also refuse to attack the two claims that are true -
which turns the usual "find the bug" incentive into a two-sided decision. The V1 witness cannot be found
by testing at all: the banding parameters put random escape at {p_rand:.0e}, so the solver has to reason
about what the signature does and engineer shingles against it.

**Truth source.** Self-evidencing. For a falsifiable claim there is no stored answer: the verifier runs
the witness and recomputes the claimed quantity independently, so the witness proves itself. For the two
claims recorded as holding, the key is backed by a {n_fuzz}-input fuzz per claim and by grading asymmetry -
a confirmed witness is accepted even against the key, so a wrong key entry can never fail a correct agent.

**Counter-shortcut evidence.** `certificate.json` records: {n_rand} random near-duplicate pairs produce
{n_rand_hits} V1 witnesses; five degenerate or out-of-scope witnesses are all rejected with reasons; the
blanket "everything is violated" and "everything holds" answers both fail; blind labelling succeeds with
probability {guess:.3f} before witnesses are even considered.
""".format(seed=seed, p_rand=p_rand, n_fuzz=n_fuzz, n_rand=n_rand, n_rand_hits=hits,
           guess=2.0 ** -len(KEY)))
    print("exported", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
